package com.hci.cyclenav;


/* GuidanceRoute.java
 * Class generated by JSONHelper from API JSON response
 * This is our java implementation of an
 * Open Guidance Services Route object 
 */
public class GuidanceRoute {

	public GuidanceRoute() {
		// TODO Auto-generated constructor stub
	}
}
